- README.md
- src/components/atoms/AnalyticsDropdown/AnalyticsDropdown.tsx
> changes done

- .scannerwork/report-task.txt
- src/constants/Apis.ts
Resolved a minor bug based on the sonarqube data.
> resolved a minor bug

- .scannerwork/report-task.txt
- src/redux/reducers/EditProductsReducers.tsx
- src/screens/Owneredititems/Useowneredititems.ts
resolved a edititemsreducer bug.
> Sonar major bugs

- src/components/atoms/DropDownComponent/DropDown.tsx
- src/components/atoms/DropDownComponent/dropdownStyles.ts
- src/constants/Apis.ts
- src/screens/Additems/Additems.tsx
Created a custom dropdown component for the dropdowns in the atoms to use this component for the every dropdown in the app
> fix(type dropdown): created a component for dropdowns in the app

- .scannerwork/report-task.txt
- src/constants/Apis.ts
- src/screens/OwnerHomepage/DashboardDetails.tsx
completed  the minor bugs part based on sonarqube.
> completed  minor bugs part based on sonarqube

- .scannerwork/report-task.txt
- src/components/atoms/AnalyticsDatePicker.tsx
- src/components/atoms/CalanderPicker.tsx
- src/components/atoms/DatePicker.tsx
- src/screens/FilteredAnalytics/FilteredAnalytics.tsx
- src/screens/OwnerHomepage/DashboardDetails.tsx
- src/screens/Owneredititems/Owneredititems.tsx
resolved 10 major bugs based on sonarqube
> resolved 10 major bugs based on sonarqube

- src/screens/Owneredititems/Owneredititems.tsx
event,outfit,type dopdowns are converted into dropdown component from atoms
> fix(edititems-dropdowns): changed the edit items dropdowns

- .scannerwork/report-task.txt
- ColorSchemeContext.js
- CustomModalContext.tsx
- src/screens/Profile/Profile.tsx
resolved a major bug in profile based on sonarqube
> resolved a major bug in profile based on sonarqube

- .scannerwork/report-task.txt
- src/screens/OwnerHomepage/useOwnerHome.ts
resolved a major bug in useIOwnerHome of empty block based on sonarqube
> resolved a major bug in useOwnerHome of empty block

- src/screens/UProductDetails/UProductDetails.tsx
resolved array index in keys in Uproductdetailspage
> resolved array index in keys in Uproductdetailspage

- .scannerwork/report-task.txt
- src/screens/Owneredititems/Owneredititems.tsx
resolved a major bug in images of owneredititems
> resolved a major bug in images of Owneredititems

- .scannerwork/report-task.txt
- src/components/atoms/PriceRange/PriceDropdown.tsx
- src/constants/Apis.ts
resolved a bug in price dropdown
> resolved a bug in price dropdown

- .scannerwork/report-task.txt
- src/redux/reducers/Additemsreducers.tsx
- src/screens/Ownereditprofile/OwnerEditProfile.tsx
- src/screens/Subcategory/Subcategory.tsx
fixed a major bug of refactoring of Ownereditprofile page has been done based on Sonarqube.
> fixed a bug of refactoring of Ownereditprofile page has been done

- .scannerwork/report-task.txt
- src/navigation/Ownerbottomtab/Ownerstack.tsx
resolved a major bug and critical bugs in ownerstack based on sonarqube.
> resolved a major bug and critical bugs in ownerstack

- .scannerwork/report-task.txt
- src/screens/OwnerImage/AddImages.tsx
Addimages Cognitive Complexity error fixed based on the Sonarqube.
> Addimages Cognitive Complexity error fixed

- .scannerwork/report-task.txt
- src/components/atoms/SubcategoryDropdown/SubcategoryDropdown.tsx
- src/constants/Apis.ts
> fix: type error in SubcategoryDropdown

- package-lock.json
- package.json
- src/constants/Apis.ts
- src/screens/FilteredAnalytics/FilteredAnalytics.tsx
resolved a major bug in filterAnaltyics
> resolved a major bug in filterAnaltyics

- src/components/atoms/AnalyticsDatePicker.tsx
> fix: type error in AnalyticsDatePicker

- .scannerwork/report-task.txt
- src/screens/CheckoutScreen/CheckoutScreenStyle.ts
duplications removed in checkout styles
> Duplications fixes

- .scannerwork/report-task.txt
- src/screens/CategoryProducts/CategoryProducts.tsx
Resolved duplication on categoryproducts page and wishlist page based on Sonarqube.
> Resolved duplication on categoryproducts page and wishlist page

- src/components/atoms/DonutChart.tsx
> fix: type error in DonutChart

- .scannerwork/report-task.txt
- src/screens/Ownerprofile/OwnerProfile.tsx
resolved a duplication error in Profile and OwnerProfile based on Sonarqube.
> resolved a duplication error in Profile and OwnerProfile

- src/components/atoms/GenderDropdown.tsx
- src/components/atoms/Sizeselect.tsx
fixed type_error in Sizeselect.tsx
> fix: type error in Sizeselect

- package-lock.json
- package.json
- src/screens/FilteredAnalytics/FilteredAnalytics.tsx
- src/screens/FilteredAnalytics/useFilteredAnalytics.ts
- src/screens/OwnerHomepage/DashboardDetails.tsx
resolved security errors in the filtered screen and dashboard screen
> Security errors

- .scannerwork/report-task.txt
- src/components/atoms/DatePickerComponent/DatepickerComponent.tsx
removed type_error and updated toggle picker
> fix: type error in DatepickerComponent is done

- src/screens/LoginScreen/useLoginscreen.ts
now the user is able to see the custom modal if user tries to sign in using wrong credentials
> fix: Custom modal in sign in page fixed

- src/screens/Additems/Additems.tsx
skeliton loader color error fixed
> skeliton loader color error fixed

- src/screens/Ownereditprofile/OwnerEditProfile.tsx
- src/screens/Wishlist/wishlistStyles.ts
resolved a colorschema textInput textcolor bug is fixed
> resolved a colorschema textInput textcolor bug is fixed

- .gitignore
- __tests__/atoms/BackButton/BackButton.test.tsx
- __tests__/atoms/Headingtext/Headingtext.test.tsx
- sonar-project.properties
- src/components/atoms/BackButton/BackButton.tsx
- src/components/atoms/HeadingText/HeadingTest.tsx
- src/constants/Apis.ts
- src/screens/FilteredAnalytics/FilteredAnalytics.tsx
- src/screens/FilteredAnalytics/useFilteredAnalytics.ts
- src/screens/OwnerHomepage/DashboardDetails.tsx
Added test cases for back button and changed the props in heading texts
> backbutton testing completed

- __tests__/atoms/SubcategoryDropdown/SubcategoryDropodown.test.tsx
- src/components/atoms/SubcategoryDropdown/SubcategoryDropdown.tsx
Added test cases for the Subcategory Dropdown
> test: Subcategory Dropdown testing done

- __tests__/constants/Regex/Regex.test.tsx
- __tests__/constants/colors/Colors.test.tsx
testing for the constants are done
> testing for the constants are done

- __tests__/redux/reducers/Additemsreducer.test.ts
additemreducer testing is done
> additemreducer testing is done

- .scannerwork/report-task.txt
- __tests__/redux/reducers/Additemsreducer.test.ts
- __tests__/redux/reducers/eventreducers.test.ts
additemsreducers and eventreducers testing is done
> additemsreducers and eventreducers testing is done

- __tests__/redux/reducers/Rolereducers.test.ts
> Rolereducer testing is done

- __tests__/redux/reducers/orderreducer.test.ts
> OrderReducer testing is Done

- __tests__/redux/Slices/edititemslice.test.ts
Testing for the Edititems slice is done
> Testing for the Edititems slice is done

- __tests__/redux/Store/Store.test.ts
- src/redux/store.tsx
> Testing for Store is Done

- __tests__/Screens/LoginScreen/LoginScreen.test.tsx
- src/constants/Apis.ts
- src/screens/Home/Homescreen.tsx
- src/screens/Home/useHome.ts
Added a New feature in search bar
> Added a New feature in search bar

- __tests__/Screens/LoginScreen/LoginScreen.test.tsx
- src/screens/LoginScreen/LoginScreen.tsx
Loginscreen testing is Done but in Branch 66% covered
> Loginscreen testing is Done but in Branch 66% covered

- ColorSchemeContext.js
- __tests__/Screens/SignupScreen/SignupScreen.test.tsx
- src/constants/Apis.ts
- src/screens/SignUp/SignupScreen.tsx
- src/screens/SignUp/useSignup.ts
useSignup testing is done upto 70 percent
> test:Signup Screen testing Done

- __tests__/Screens/LoginScreen/LoginScreen.test.tsx
- src/constants/Apis.ts
- src/screens/LoginScreen/LoginScreen.tsx
- src/screens/LoginScreen/useLoginscreen.ts
Testing for the LoginScreen is DOne with 87.5%
> Testing for the LoginScreen is DOne with 87.5%

- __tests__/UnitTest/SignupScreen/Signupscreen.test.tsx
- __tests__/UnitTest/SignupScreen/useSignup.test.tsx
- package-lock.json
- package.json
- src/constants/Apis.ts
- src/screens/SignUp/SignupScreen.tsx
- src/screens/SignUp/useSignup.ts
Added testing for usehook and unit testing separately
> Unit testes added separately for signup screen

- __tests__/Screens/LoginScreen/LoginScreenIntegrationtest.test.tsx
- __tests__/Screens/LoginScreen/LoginScreenunittest.test.tsx
- __tests__/Screens/subCategoryScreen/SubcategoryScreen.test.tsx
- src/constants/Apis.ts
- src/screens/LoginScreen/LoginScreen.tsx
- src/screens/LoginScreen/useLoginscreen.ts
- src/screens/Subcategory/Subcategory.tsx
LoginScreen Testing is Done for both (unit test and integration test)
> LoginScreen Testing is Done for both (unit test and integration test)

- __tests__/Screens/Category/Category.test.tsx
- __tests__/Screens/Category/useCategory.test.tsx
- src/screens/Category/useCategory.ts
changed the fetchcategories to Api service and testing for the api is done
> test: useCategory hook testing is done

- __tests__/Screens/subCategoryScreen/SubcategoryScreen.test.tsx
- __tests__/Screens/subCategoryScreen/Subcategoryunittest.test.tsx
- src/screens/Subcategory/Subcategory.tsx
Subcategory Page testing is Done
> Subcategory Page testing is Done

- __tests__/Screens/Cart/CartScreen.test.tsx
- __tests__/Screens/Cart/useCart.test.tsx
- src/constants/Apis.ts
- src/screens/Cart/Cart.tsx
- src/screens/Cart/useCart.tsx
- src/screens/CheckoutScreen/useCheckout.ts
cart screen : testing done 90%
useCart screen: testing done and changed the api methods to Apiservice
> test: Cart screen testing done 90%

- __tests__/Screens/OtpScreen/OtpScreen.test.tsx
- __tests__/Screens/SearchResultScreen/SearchResultScreenunittest.test.tsx
- src/constants/Apis.ts
- src/screens/OtpScreen/OtpScreen.tsx
- src/screens/SearchResultScreen/SearchResultScreen.tsx
- src/screens/Wishlist/Wishlist.tsx
Testing completed for OTPscreen(100%), searchResultsScreen(90%) are Done
> Testing completed for OTPscreen(100%), searchResultsScreen(90%) are Done

- __tests__/Screens/EditAddress/EditAddress.test.tsx
- __tests__/Screens/EditAddress/useEditAddress.test.tsx
- src/screens/EditAddress/EditAddress.tsx
- src/screens/EditAddress/useEditAddress.ts
- src/screens/Owneraddaddress/AddAddress.tsx
- src/screens/Owneraddaddress/Address.tsx
Edit Address testing is done with 100% but branches left.
> test: EditAddress tesing is done

- .scannerwork/report-task.txt
- ColorSchemeContext.js
- __tests__/Screens/EditProfile/EditprofilescreenIntegrationtest.test.tsx
- __tests__/Screens/EditProfile/Editprofilescreenunittest.test.tsx
- __tests__/Screens/SearchResultScreen/SearchResultScreenunittest.test.tsx
- __tests__/Screens/wishlistScreen/Wishlistscreenunittest.test.tsx
- src/constants/Apis.ts
- src/screens/Category/Category.tsx
- src/screens/Ownereditprofile/OwnerEditProfile.tsx
- src/screens/Ownereditprofile/useOwnerProfile.ts
SearchResultsScreen 90% and editprofile screen 85% done
> SearchResultsScreen 90% and editprofile screen 85% done

- __tests__/Screens/wishlistScreen/Wishlistscreenunittest.test.tsx
- src/constants/Apis.ts
Test: testing for the wishlist is done for 80%
> Test: testing for the wishlist is done for 80%

- ColorSchemeContext.js
- __tests__/Screens/wishlistScreen/Wishlistscreenunittest.test.tsx
- src/screens/Wishlist/Wishlist.tsx
- src/screens/Wishlist/useWishlist.ts
Test: Testing is Done for Wishlist Screen
> Test: Testing is Done for Wishlist Screen

- App.tsx
- __tests__/Screens/subCategoryScreen/SubcategoryScreen.test.tsx
- __tests__/Screens/subCategoryScreen/Subcategoryscreenunittest.test.tsx
- src/constants/Apis.ts
- src/redux/actions/actions.ts
- src/screens/Subcategory/Subcategory.tsx
Bug: resolved bugs in onboarding, subcategory screen.
> Bug: resolved bugs in onboarding, subcategory screen.

- __tests__/Screens/checkoutScreen/checkoutScreenUnittest.test.tsx
- src/screens/CheckoutScreen/CheckoutScreen.tsx
Test : testing for checkout is done 58%
> Test : testing for checkout is done 58%
